### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by mickeyvip** [jaredramirez/reason-elm-example#1]
Hi, I am very new to Reason and I copied your example into auto generated ReasonML project.

I get this error:
![image](https://user-images.githubusercontent.com/220427/35286285-3f8aea12-0068-11e8-8969-0eac8b65da84.png)

I suppose I am doing something wrong, but I have no idea what.

**Comment by mickeyvip** [comment]
Found my mistake:

I had `elmProgram` instead of `elmProgramWithPorts(ports)`.

**Comment by jaredramirez** [comment]
Thanks for letting me know! I am in the processes of rethinking the way to interact with ports, so that errors like this are more clear!
